// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qatshjlkxjohlmywampy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhdHNoamxreGpvaGxteXdhbXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MTY5MzUsImV4cCI6MjA1NzM5MjkzNX0.ga_wBeyayMpkAl_ovz8ysR1uHDB91Q4LDdH3L_UHQRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);